import type { Feature } from "geojson";
import { constructMatchExpression } from "svelte-utils/map";
import type { ExpressionSpecification } from "maplibre-gl";

/** Length in meters above which a crossing-tagged way is considered suspicious (may need splitting). */
export const CROSSING_LENGTH_WARNING_M = 20;

export interface NodeProps {
  id: number;
  tags?: Record<string, string>;
  is_crossing: boolean;
  is_explicit_crossing_no: boolean;
  is_generated_crossing?: boolean;
  is_manual_crossing?: boolean;
  modified: boolean;
  way_ids: number[];
  problems: Problem[];
}

export interface WayProps {
  id: number;
  tags: Record<string, string>;
  length_m?: number;
  kind:
    | "RoadWithSeparate"
    | "RoadWithTags"
    | "RoadWithoutSidewalksExplicit"
    | "RoadWithoutSidewalksImplicit"
    | "RoadUnknown"
    | "Sidewalk"
    | "Crossing"
    | "Other";
  modified: boolean;
  node_ids: number[];
  is_severance: boolean;
  is_service: boolean;
  is_manual_crossing?: boolean;
  problems: Problem[];
}

interface Problem {
  note: string;
  details: Feature[];
}

export let colors = {
  RoadWithSeparate: "purple",
  RoadWithTags: "blue",
  RoadWithoutSidewalksExplicit: "#8B4000",
  RoadWithoutSidewalksImplicit: "orange",
  RoadUnknown: "#ff69b4",

  Sidewalk: "black",
  Crossing: "green",
  Other: "grey",
};

const sideColorRgb = {
  left: [255, 105, 180], // pink
  right: [32, 178, 170], // teal
} as const;

export function sideColorMaplibre(
  side: keyof typeof sideColorRgb,
  opacity: number = 1.0,
): ["rgba", number, number, number, number] {
  return ["rgba", ...sideColorRgb[side], opacity] as const;
}

export function siteColorRgba(
  side: keyof typeof sideColorRgb,
  opacity: number = 1.0,
): string {
  const [r, g, b] = sideColorRgb[side];
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}

export let kindLabels = {
  RoadWithSeparate: "With separate sidewalks",
  RoadWithTags: "With tagged sidewalks",
  RoadWithoutSidewalksExplicit: "Tagged as no sidewalks",
  RoadWithoutSidewalksImplicit: "Assumed as no sidewalks",
  RoadUnknown: "Totally unknown",
  Sidewalk: "Separate sidewalk",
  Crossing: "Crossing",
  Other: "Other",
};

/** Ordered kinds for roads and non-roads; shared by Sidewalks and Export legend/metrics. */
export const roadKinds = [
  "RoadWithSeparate",
  "RoadWithTags",
  "RoadWithoutSidewalksExplicit",
  "RoadWithoutSidewalksImplicit",
  "RoadUnknown",
] as const;
export const nonRoadKinds = ["Sidewalk", "Crossing", "Other"] as const;

type RoadKind = (typeof roadKinds)[number];
type NonRoadKind = (typeof nonRoadKinds)[number];
type LegendKind = RoadKind | NonRoadKind;

/** Legend items (label + color) for sidewalk/road kinds; same terms and colors on Export and Sidewalks. */
export const sidewalkLegendItems: { label: string; color: string }[] = [
  ...roadKinds,
  ...nonRoadKinds,
].map((kind: LegendKind) => ({
  label: kindLabels[kind],
  color: colors[kind],
}));

/** Shared legend colors for Generator "Roads" (major vs minor by is_severance). Reuses same hex as road kinds. */
export const roadLegendColors = {
  "Major roads": "purple",
  "Minor roads": "blue",
} as const;

/** Shared legend colors for Generator "Sidewalks" (OSM vs generated by modified). */
export const sidewalkLegendColors = {
  "Sidewalks from OSM": "black",
  "Generated sidewalks": "cyan",
} as const;

// Zoom-dependant line width, adapted from from the Minor road layer (secondary
// road class) from https://api.maptiler.com/maps/streets-v2/style.json. At
// high zoom, make sidewalks, crossings, and other roads thinner.
export function roadLineWidth(extraWidth: number): ExpressionSpecification {
  return [
    "interpolate",
    ["linear"],
    ["zoom"],
    5,
    0.5 + extraWidth,
    10,
    1 + extraWidth,
    12,
    1.5 + extraWidth,
    14,
    4 + extraWidth,
    16,
    constructMatchExpression(
      ["get", "kind"],
      {
        Sidewalk: 4 + extraWidth,
        Crossing: 5 + extraWidth,
        Other: 5 + extraWidth,
      },
      7 + extraWidth,
    ),
    20,
    constructMatchExpression(
      ["get", "kind"],
      {
        Sidewalk: 7 + extraWidth,
        Crossing: 10 + extraWidth,
        Other: 10 + extraWidth,
      },
      24 + extraWidth,
    ),
  ] as ExpressionSpecification;
}
